<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="ExerciseExternalFireControlParametersFB" Id="{f582d874-d478-4b4a-9f84-78fe9777f030}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ExerciseExternalFireControlParametersFB
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>