<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="DefaultParametersFB" Id="{4975ba0a-01f7-4cdb-a2ac-96db5e0f2562}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK DefaultParametersFB
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>