<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="State" Id="{9dbb020e-07f3-49c6-9250-91502d4b2d6f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK State
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Run" Id="{664c0116-4061-4da4-9554-8fa83562b818}">
      <Declaration><![CDATA[METHOD Run : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Start" Id="{2d8f2914-360e-48d1-b86f-5b084ae01727}">
      <Declaration><![CDATA[METHOD Start : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stop" Id="{c35322c8-340e-4abf-9743-94423fed4e20}">
      <Declaration><![CDATA[METHOD Stop : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Transition" Id="{f74520f1-202a-4ad8-9598-49eadd8359d5}">
      <Declaration><![CDATA[METHOD Transition : POINTER TO State
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Transition := ADR(THIS^);
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="State">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="State.Run">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="State.Start">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="State.Stop">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="State.Transition">
      <LineId Id="5" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>