<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="SimulationParametersFB" Id="{90e29d7f-5bc4-4458-b73f-f4191c455abb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK SimulationParametersFB
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SimCounter := SimCounter + 1;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>