<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="ModbusWriteWord" Id="{53d5e34b-aeae-47d4-a08b-e0c8ea184e2e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ModbusWriteWord EXTENDS ModbusIo
VAR_INPUT
	Value: WORD;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();
]]></ST>
    </Implementation>
    <LineIds Name="ModbusWriteWord">
      <LineId Id="18" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>