<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="SpecificFanPower" Id="{953b4b95-9e24-49ca-9799-05c35d71dc6f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK SpecificFanPower
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="SpecificFanPower">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>