<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="NetLinkParametersFB" Id="{70d71791-c95b-4941-80ac-0ecb7778050c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK NetLinkParametersFB
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Update" Id="{d2b89ff4-bc7c-4576-a53f-0863be15f6a0}">
      <Declaration><![CDATA[METHOD Update : BOOL
VAR_INPUT
	Parameters: REFERENCE TO GreenMasterBaseParameters;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>