<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="SmokeControlParametersBaseFB" Id="{cb2dd51e-9b1a-47f2-beaa-8e08fc084563}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK SmokeControlParametersBaseFB
VAR_INPUT
END_VAR
VAR_OUTPUT
	NetLink: NetLinkParametersFB;
	DamperModules: SxDuoParametersFB;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>