<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="FireDamper" Id="{83eb272c-0be2-4677-9ef1-4597c43233af}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FireDamper EXTENDS Damper
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FireDamper">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>