<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="OperationParametersFB" Id="{e5945a20-31af-4e0c-b485-efd698d245e4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK OperationParametersFB
VAR_INPUT
	Parameters: REFERENCE TO GreenMasterBaseParameters;
	ParametersFB: REFERENCE TO GreenMasterBaseParametersFB;
END_VAR
VAR_OUTPUT
	TimeChannelsParametersFB: TimeChannelParametersFB;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TimeChannelsParametersFB(Parameters := Parameters, ParametersFB := ParametersFB);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>