<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="TimeChannelDayParametersFB" Id="{949eff14-5f79-4ead-9ef7-98a87554a224}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TimeChannelDayParametersFB
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>