<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="GetTickCount" Id="{60465d36-94d5-4bba-aeb4-47818b21e733}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION GetTickCount : LINT
VAR_INPUT
END_VAR
VAR
	
END_VAR
VAR_STAT
	GST: Tc2_System.GETCPUCOUNTER;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[GST();
GetTickCount := LWORD_TO_LINT(((DWORD_TO_LWORD(GST.cpuCntHiDW) * 16#100000000) + GST.cpuCntLoDW)) / 10000;
]]></ST>
    </Implementation>
    <LineIds Name="GetTickCount">
      <LineId Id="3" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>