<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="LREAL_TO_WORD_SAFE" Id="{ad541bb9-12e5-4b60-a961-3b7d84739031}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION LREAL_TO_WORD_SAFE : WORD
VAR_INPUT
	Value: LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[LREAL_TO_WORD_SAFE := TO_WORD(TO_LINT(Value));
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>